// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caipxjciwpyltxzxukbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhaXB4amNpd3B5bHR4enh1a2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTQxMjksImV4cCI6MjA3MTg5MDEyOX0.nEAbCVBRx_a31tqomCq4vZ8lzppXHU78KEhHSmyDNBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});